stages:
  preprocess:
    cmd: python3 src/data/preprocess.py --img-size 224 --raw-dir data/raw --out-dir data/processed
    deps:
      - data/raw
      - src/data/preprocess.py
    outs:
      - data/processed
  
  train:
    cmd: python3 src/training/train.py --epochs ${train.epochs} --img-size ${train.img_size} --batch ${train.batch}
    deps:
      - data/processed
      - src/training/train.py
    outs:
      - data/yolo
      - runs
      - mlflow_run.txt
    metrics:
      - metrics.json:
          cache: false
  report:
    cmd: python3 src/training/report.py
    deps:
      - runs
      - metrics.json
      - src/training/report.py
    outs:
      - mlflow_run_official.txt:
          cache: false
    always_changed: true
