[project]
name = "pcb-defect-mlops-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlflow==2.22.1",
    "opencv-python-headless>=4.8.0",
    "ultralytics>=8.1.0",
    "dvc[s3]>=3.0.0",
    "python-dotenv>=1.0.0",
    "tqdm>=4.66.0",
    "numpy>=1.24.0",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
    "streamlit>=1.25.0",
    "python-multipart>=0.0.6",
    "label-studio-sdk>=2.0.0",
    "pyyaml>=6.0.0",
    "boto3>=1.34.0",
    "evidently>=0.4.0",
    "onnx>=1.16.1",
    "onnxruntime>=1.16.0",
    "onnxslim>=0.1.71",
    "ml-dtypes>=0.5.0"
]
