services:
  # Unified MLflow Instance
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    user: "501:20"
    ports:
      - "5555:5000"
    working_dir: /mlflow/data
    environment:
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
      - MLFLOW_S3_ENDPOINT_URL=http://rustfs:9000
      - MLFLOW_S3_IGNORE_TLS=true
    volumes:
      - ../mlflow-history:/mlflow/data
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////mlflow/data/mlflow.db --default-artifact-root mlflow-artifacts:/ --serve-artifacts

  # Official MLflow for Team/Professor
  mlflow-official:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-official
    user: "501:20"
    ports:
      - "5556:5000"
    working_dir: /mlflow/data
    environment:
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
      - MLFLOW_S3_ENDPOINT_URL=http://rustfs:9000
      - MLFLOW_S3_IGNORE_TLS=true
    volumes:
      - ../mlflow-official-history:/mlflow/data
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////mlflow/data/mlflow.db --default-artifact-root mlflow-artifacts:/ --serve-artifacts

  # Human-in-the-Loop Labeling
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ../label_studio_data:/label-studio/data
      - ../data:/label-studio/data/projects-data
    environment:
      - DJANGO_DB=default
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data/projects-data

  # S3 Compatible Storage (RustFS)
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_VOLUMES=/data
    volumes:
      - ../dvc-storage:/data

  # Apache Airflow Standalone
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    ports:
      - "8085:8080"
    user: "501:20"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/project/dags
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas numpy requests label-studio-sdk python-dotenv dvc[s3]
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - LABEL_STUDIO_URL=http://label-studio:8080
      - LABEL_STUDIO_API_KEY=4c5c6e9a5c5c42458204e855a68a0fcd4c5c6e9a
      - LABEL_STUDIO_PROJECT_ID=1
      - DVC_REMOTE_PCB_VAULT_ENDPOINTURL=http://rustfs:9000
      - DVC_REMOTE_LOGS_STORAGE_ENDPOINTURL=http://rustfs:9000
      - DVC_REMOTE_MODELS_STORAGE_ENDPOINTURL=http://rustfs:9000
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
    volumes:
      - ..:/opt/airflow/project
    working_dir: /opt/airflow/project
    command: standalone

